export const APP_ACTION = {
  SET_HEADER_TEXT: "SET_HEADER_TEXT",
  SHOW_LOADING: "SHOW_LOADING",
  HIDE_LOADING: "HIDE_LOADING"
};

export const MEMBER_ACTION = {
  LOAD_LOGIN_MEMBER_DETAIL_SUCCESS: "MEMBER_DETAIL_DATA",
  LOGIN_SUCCESS: "LOGIN_SUCCESS",
  LOGIN_FIELD_CHANGE_SUCCESS: "LOGIN_FIELD_CHANGE_SUCCESS"
};

export const LOCALE_ACTION = {
  CHANGE_LOCATE_SUCCESS: "CHANGE_LOCATE_SUCCESS"
};